# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubUsers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubUsers
  pod 'TagListView', '~> 1.0'
  pod 'Alamofire'

  target 'GitHubUsersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubUsersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
